import { create } from 'zustand';

type Lang = 'hi' | 'en';

interface LanguageStore {
  lang: Lang;
  toggle: () => void;
}

export const useLanguageStore = create<LanguageStore>((set) => ({
  lang: (localStorage.getItem('rozgar_lang') as Lang) || 'hi',
  toggle: () => set((s) => {
    const next = s.lang === 'hi' ? 'en' : 'hi';
    localStorage.setItem('rozgar_lang', next);
    return { lang: next };
  }),
}));

const translations: Record<string, Record<Lang, string>> = {
  'रजिस्टर करें': { hi: 'रजिस्टर करें', en: 'Register' },
  'नक्शा': { hi: 'नक्शा', en: 'Map' },
  'About Us': { hi: 'हमारे बारे में', en: 'About Us' },
  'Admin Panel': { hi: 'एडमिन पैनल', en: 'Admin Panel' },
  'बुकिंग': { hi: 'बुकिंग', en: 'Bookings' },
  'कमाई': { hi: 'कमाई', en: 'Earnings' },
  'मेनू': { hi: 'मेनू', en: 'Menu' },
  'लॉगआउट': { hi: 'लॉगआउट', en: 'Logout' },
  'लॉगिन करें': { hi: 'लॉगिन करें', en: 'Login' },
  'होम पेज': { hi: 'होम पेज', en: 'Home' },
  'काम ढूंढें': { hi: 'काम ढूंढें', en: 'Find Work' },
  'खोज': { hi: 'खोज', en: 'Search' },
  'त्वरित खोज': { hi: 'त्वरित खोज', en: 'Quick Search' },
  'काम के प्रकार': { hi: 'काम के प्रकार', en: 'Work Types' },
  'गाँव / शहर': { hi: 'गाँव / शहर', en: 'Village / City' },
  'GPS नज़दीक': { hi: 'GPS नज़दीक', en: 'Nearby GPS' },
  'लोकप्रिय सेवाएँ': { hi: 'लोकप्रिय सेवाएँ', en: 'Popular Services' },
  'सभी देखें': { hi: 'सभी देखें', en: 'View All' },
  'सभी श्रेणियाँ': { hi: 'सभी श्रेणियाँ', en: 'All Categories' },
  'क्या आप कामगार हैं?': { hi: 'क्या आप कामगार हैं?', en: 'Are you a worker?' },
  'मुफ्त में रजिस्टर करें और स्थानीय काम पाएं': { hi: 'मुफ्त में रजिस्टर करें और स्थानीय काम पाएं', en: 'Register for free and find local work' },
  'अभी रजिस्टर करें': { hi: 'अभी रजिस्टर करें', en: 'Register Now' },
  'हम पर भरोसा करें': { hi: 'हम पर भरोसा करें', en: 'Trust Us' },
  'ऐप शेयर करें': { hi: 'ऐप शेयर करें', en: 'Share App' },
  'श्रेणियाँ': { hi: 'श्रेणियाँ', en: 'Categories' },
  'कामगार': { hi: 'कामगार', en: 'Workers' },
  'उपयोग': { hi: 'उपयोग', en: 'Usage' },
  'मुफ्त': { hi: 'मुफ्त', en: 'Free' },
  'नज़दीकी सेवाएँ': { hi: 'नज़दीकी सेवाएँ', en: 'Nearby Services' },
  'सभी': { hi: 'सभी', en: 'All' },
  'दुकान': { hi: 'दुकान', en: 'Shop' },
  'डिजिटल': { hi: 'डिजिटल', en: 'Digital' },
  'कोचिंग': { hi: 'कोचिंग', en: 'Coaching' },
  'कॉल': { hi: 'कॉल', en: 'Call' },
  'रास्ता': { hi: 'रास्ता', en: 'Route' },
  'प्रोफ़ाइल देखें': { hi: 'प्रोफ़ाइल देखें', en: 'View Profile' },
  'रजिस्ट्रेशन': { hi: 'रजिस्ट्रेशन', en: 'Registration' },
  'सेवाएँ': { hi: 'सेवाएँ', en: 'Services' },
  'लोकेशन ले रहे हैं...': { hi: 'लोकेशन ले रहे हैं...', en: 'Getting location...' },
  'अपनी लोकेशन जोड़ें': { hi: 'अपनी लोकेशन जोड़ें', en: 'Add your location' },
  // Registration form translations
  'कामगार रजिस्ट्रेशन': { hi: 'कामगार रजिस्ट्रेशन', en: 'Worker Registration' },
  'कामगार के रूप में रजिस्टर करें': { hi: 'कामगार के रूप में रजिस्टर करें', en: 'Register as a worker' },
  'प्रोफ़ाइल फोटो (वैकल्पिक)': { hi: 'प्रोफ़ाइल फोटो (वैकल्पिक)', en: 'Profile Photo (Optional)' },
  'पूरा नाम': { hi: 'पूरा नाम', en: 'Full Name' },
  'अपना नाम लिखें': { hi: 'अपना नाम लिखें', en: 'Enter your name' },
  'मोबाइल नंबर': { hi: 'मोबाइल नंबर', en: 'Mobile Number' },
  '10 अंकों का मोबाइल नंबर': { hi: '10 अंकों का मोबाइल नंबर', en: '10-digit mobile number' },
  'कार्य श्रेणी': { hi: 'कार्य श्रेणी', en: 'Work Type' },
  'श्रेणी चुनें': { hi: 'श्रेणी चुनें', en: 'Select Category' },
  'अपनी श्रेणी लिखें': { hi: '+ अपनी श्रेणी लिखें (Custom)', en: '+ Write your category (Custom)' },
  'सूची में से चुनें': { hi: '← सूची में से चुनें', en: '← Select from list' },
  'अपनी कार्य श्रेणी लिखें': { hi: 'अपनी कार्य श्रेणी लिखें', en: 'Write your work category' },
  'अपने गाँव का नाम': { hi: 'अपने गाँव का नाम', en: 'Your village name' },
  'अनुभव (वर्ष)': { hi: 'अनुभव (वर्ष)', en: 'Experience (Years)' },
  'कितने वर्षों का अनुभव': { hi: 'कितने वर्षों का अनुभव', en: 'Years of experience' },
  'सेवा शुल्क रेंज (₹) — वैकल्पिक': { hi: 'सेवा शुल्क रेंज (₹) — वैकल्पिक', en: 'Service Charge Range (₹) — Optional' },
  'न्यूनतम ₹': { hi: 'न्यूनतम ₹', en: 'Min ₹' },
  'अधिकतम ₹': { hi: 'अधिकतम ₹', en: 'Max ₹' },
  'या टेक्स्ट में लिखें:': { hi: 'या टेक्स्ट में लिखें:', en: 'Or write in text:' },
  'जैसे: ₹300/दिन': { hi: 'जैसे: ₹300/दिन', en: 'e.g. ₹300/day' },
  'उपलब्ध समय': { hi: 'उपलब्ध समय', en: 'Available Time' },
  'सुबह': { hi: 'सुबह', en: 'Morning' },
  'दोपहर': { hi: 'दोपहर', en: 'Afternoon' },
  'शाम': { hi: 'शाम', en: 'Evening' },
  'पूरा दिन': { hi: 'पूरा दिन', en: 'Full Day' },
  'GPS लोकेशन (वैकल्पिक)': { hi: '📍 GPS लोकेशन (वैकल्पिक)', en: '📍 GPS Location (Optional)' },
  'अपने बारे में': { hi: 'अपने बारे में', en: 'About Yourself' },
  'अपने कौशल का संक्षिप्त विवरण': { hi: 'अपने कौशल का संक्षिप्त विवरण', en: 'Brief description of your skills' },
  'सीक्रेट PIN बनाएं (4 अंक)': { hi: '🔒 सीक्रेट PIN बनाएं (4 अंक)', en: '🔒 Create Secret PIN (4 digits)' },
  'प्रोफ़ाइल एडिट/डिलीट करने के लिए PIN ज़रूरी है': { hi: 'प्रोफ़ाइल एडिट/डिलीट करने के लिए PIN ज़रूरी है', en: 'PIN is required to edit/delete profile' },
  'PIN डालें': { hi: 'PIN डालें', en: 'Enter PIN' },
  'PIN दोबारा डालें': { hi: 'PIN दोबारा डालें', en: 'Confirm PIN' },
  'रजिस्टर हो रहा है...': { hi: 'रजिस्टर हो रहा है...', en: 'Registering...' },
  'रजिस्ट्रेशन सफल!': { hi: 'रजिस्ट्रेशन सफल!', en: 'Registration Successful!' },
  'आपकी प्रोफ़ाइल अब लाइव है।': { hi: 'आपकी प्रोफ़ाइल अब लाइव है।', en: 'Your profile is now live.' },
  'कामगार देखें': { hi: 'कामगार देखें', en: 'View Workers' },
  'कृपया 4 अंकों का PIN डालें': { hi: 'कृपया 4 अंकों का PIN डालें', en: 'Please enter a 4-digit PIN' },
  'PIN मेल नहीं खाता': { hi: 'PIN मेल नहीं खाता', en: 'PINs do not match' },
  'रजिस्ट्रेशन में समस्या हुई': { hi: 'रजिस्ट्रेशन में समस्या हुई', en: 'Registration failed' },
  'अन्य (Other)': { hi: 'अन्य (Other)', en: 'Other' },
  // Booking page
  'बुकिंग इतिहास': { hi: 'बुकिंग इतिहास', en: 'Booking History' },
  'अपनी पिछली बुकिंग देखें': { hi: 'अपनी पिछली बुकिंग देखें', en: 'View your past bookings' },
  'ग्राहक': { hi: 'ग्राहक', en: 'Customer' },
  'बुकिंग देखें': { hi: 'बुकिंग देखें', en: 'View Bookings' },
  'कोई बुकिंग नहीं मिली': { hi: 'कोई बुकिंग नहीं मिली', en: 'No bookings found' },
  'कॉल करें': { hi: 'कॉल करें', en: 'Call' },
  'नंबर बदलें': { hi: 'नंबर बदलें', en: 'Change Number' },
  'ग्राहक के रूप में देखें': { hi: 'ग्राहक के रूप में देखें', en: 'View as Customer' },
  'कामगार के रूप में देखें': { hi: 'कामगार के रूप में देखें', en: 'View as Worker' },
  // Earnings page
  'कमाई डैशबोर्ड': { hi: 'कमाई डैशबोर्ड', en: 'Earnings Dashboard' },
  'अपनी बुकिंग और काम का विवरण देखें': { hi: 'अपनी बुकिंग और काम का विवरण देखें', en: 'View your booking and work details' },
  'अपना मोबाइल नंबर डालें': { hi: '📱 अपना मोबाइल नंबर डालें', en: '📱 Enter your mobile number' },
  'डैशबोर्ड देखें': { hi: 'डैशबोर्ड देखें', en: 'View Dashboard' },
  'खोज रहे हैं...': { hi: 'खोज रहे हैं...', en: 'Searching...' },
  'आज के काम': { hi: 'आज के काम', en: 'Today\'s Jobs' },
  'इस महीने': { hi: 'इस महीने', en: 'This Month' },
  'इस साल': { hi: 'इस साल', en: 'This Year' },
  'कुल काम': { hi: 'कुल काम', en: 'Total Jobs' },
  'कुल': { hi: 'कुल', en: 'Total' },
  'पूर्ण': { hi: 'पूर्ण', en: 'Done' },
  'लंबित': { hi: 'लंबित', en: 'Pending' },
  'रद्द': { hi: 'रद्द', en: 'Cancelled' },
  // Search page
  'कामगार खोजें': { hi: 'कामगार खोजें', en: 'Find Workers' },
  'अपने आस-पास कुशल कामगार खोजें': { hi: 'अपने आस-पास कुशल कामगार खोजें', en: 'Find skilled workers near you' },
  'गाँव से खोजें...': { hi: 'गाँव से खोजें...', en: 'Search by village...' },
  'नाम से खोजें...': { hi: 'नाम से खोजें...', en: 'Search by name...' },
  'अधिक फ़िल्टर': { hi: 'अधिक फ़िल्टर', en: 'More Filters' },
  'फ़िल्टर बंद करें': { hi: 'फ़िल्टर बंद करें', en: 'Close Filters' },
  'कोई परिणाम नहीं मिला': { hi: 'कोई परिणाम नहीं मिला', en: 'No results found' },
  'अलग फ़िल्टर आज़माएं या खोज बदलें': { hi: 'अलग फ़िल्टर आज़माएं या खोज बदलें', en: 'Try different filters or change search' },
  'दुकानें, डिजिटल सेवाएँ, शिक्षा': { hi: 'दुकानें, डिजिटल सेवाएँ, शिक्षा', en: 'Shops, Digital Services, Education' },
  'सेवा प्रदाता': { hi: 'सेवा प्रदाता', en: 'Service Providers' },
  // Location labels
  'गाँव': { hi: 'गाँव', en: 'Village' },
  'स्थान': { hi: 'स्थान', en: 'Location' },
  'शहर': { hi: 'शहर', en: 'City' },
  'दूर': { hi: 'दूर', en: 'away' },
  'दुकान सेवा': { hi: 'दुकान', en: 'Shop' },
  'डिजिटल सेवा': { hi: 'डिजिटल सेवा', en: 'Digital Service' },
  'शिक्षा': { hi: 'शिक्षा', en: 'Education' },
  'Reset': { hi: 'रीसेट', en: 'Reset' },
};

export const t = (key: string, lang: Lang): string => {
  return translations[key]?.[lang] || key;
};
