// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-workers.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-workers.ts
var search_workers_default = defineTool({
  name: "search_workers",
  title: "Search workers",
  description: "Search RozgarSewa workers (plumbers, electricians, carpenters, etc.) by category, village, or name. Returns public listing details only.",
  inputSchema: {
    category: z.string().trim().optional().describe("Work category, e.g. Plumber, Electrician, Painter."),
    village: z.string().trim().optional().describe("Village or town name to filter by."),
    name: z.string().trim().optional().describe("Partial worker name to search for."),
    limit: z.number().int().optional().describe("Maximum number of workers to return (default 20, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, village, name, limit }) => {
    const take = Math.min(Math.max(limit ?? 20, 1), 50);
    let query = supabaseAnon().from("workers").select(
      "id, name, village, category, experience, about, service_charge, price_min, price_max, availability, status, created_at"
    ).order("created_at", { ascending: false }).limit(take);
    if (category) query = query.ilike("category", `%${category}%`);
    if (village) query = query.ilike("village", `%${village}%`);
    if (name) query = query.ilike("name", `%${name}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { workers: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-worker.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_worker_default = defineTool2({
  name: "get_worker",
  title: "Get worker profile",
  description: "Get the full public profile of one RozgarSewa worker by id, including experience, pricing, availability, ratings and reviews.",
  inputSchema: {
    id: z2.string().trim().min(1).describe("The worker's id (uuid) from search_workers.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const { data, error } = await supabaseAnon().from("workers").select(
      "id, name, village, category, experience, about, photo, gallery, service_charge, price_min, price_max, availability, status, ratings, reviews, created_at"
    ).eq("id", id).maybeSingle();
    if (error) throw new ToolError(error.message);
    if (!data) throw new ToolError(`No worker found with id ${id}`);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { worker: data }
    };
  }
});

// src/lib/mcp/tools/search-businesses.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var search_businesses_default = defineTool3({
  name: "search_businesses",
  title: "Search local businesses",
  description: "Search public RozgarSewa local business listings (shops, construction, agriculture, vehicle and home services) by category or village.",
  inputSchema: {
    category: z3.string().trim().optional().describe("Business category to filter by, e.g. Shop, Construction."),
    village: z3.string().trim().optional().describe("Village or town name to filter by."),
    limit: z3.number().int().optional().describe("Maximum number of businesses to return (default 20, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, village, limit }) => {
    const take = Math.min(Math.max(limit ?? 20, 1), 50);
    let query = supabaseAnon().from("local_businesses").select("id, name, category, village, address, description, created_at").order("created_at", { ascending: false }).limit(take);
    if (category) query = query.ilike("category", `%${category}%`);
    if (village) query = query.ilike("village", `%${village}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { businesses: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/search-digital-services.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var search_digital_services_default = defineTool4({
  name: "search_digital_services",
  title: "Search digital service centres",
  description: "Search public RozgarSewa digital service listings (online forms, printing, Aadhaar/PAN work) by service type or village.",
  inputSchema: {
    service_type: z4.string().trim().optional().describe("Service type to filter by, e.g. Printing, Online Form."),
    village: z4.string().trim().optional().describe("Village or town name to filter by."),
    limit: z4.number().int().optional().describe("Maximum number of listings to return (default 20, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ service_type, village, limit }) => {
    const take = Math.min(Math.max(limit ?? 20, 1), 50);
    let query = supabaseAnon().from("digital_services").select("id, shop_name, owner_name, service_type, village, address, description, created_at").order("created_at", { ascending: false }).limit(take);
    if (service_type) query = query.ilike("service_type", `%${service_type}%`);
    if (village) query = query.ilike("village", `%${village}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { services: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/search-coaching-centres.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var search_coaching_centres_default = defineTool5({
  name: "search_coaching_centres",
  title: "Search coaching centres",
  description: "Search public RozgarSewa education and coaching listings by course type or village, including fees and timings.",
  inputSchema: {
    course_type: z5.string().trim().optional().describe("Course type to filter by, e.g. Computer, Maths, Spoken English."),
    village: z5.string().trim().optional().describe("Village or town name to filter by."),
    limit: z5.number().int().optional().describe("Maximum number of listings to return (default 20, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ course_type, village, limit }) => {
    const take = Math.min(Math.max(limit ?? 20, 1), 50);
    let query = supabaseAnon().from("education_coaching").select("id, institute_name, owner_name, course_type, village, address, description, fees, timing, created_at").order("created_at", { ascending: false }).limit(take);
    if (course_type) query = query.ilike("course_type", `%${course_type}%`);
    if (village) query = query.ilike("village", `%${village}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { centres: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^4.4.3";
var list_categories_default = defineTool6({
  name: "list_categories",
  title: "List categories",
  description: "List the work and business categories that currently have listings on RozgarSewa, with a count for each.",
  inputSchema: {
    kind: z6.enum(["workers", "businesses", "all"]).optional().describe("Which listings to summarise: workers, businesses, or all (default).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ kind }) => {
    const which = kind ?? "all";
    const supabase = supabaseAnon();
    const tally = (rows) => {
      const counts = {};
      for (const row of rows ?? []) {
        const key = (row.category ?? "").trim() || "Other";
        counts[key] = (counts[key] ?? 0) + 1;
      }
      return Object.entries(counts).map(([category, count]) => ({ category, count })).sort((a, b) => b.count - a.count);
    };
    const result = {};
    if (which === "workers" || which === "all") {
      const { data, error } = await supabase.from("workers").select("category").limit(1e3);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      result.workers = tally(data);
    }
    if (which === "businesses" || which === "all") {
      const { data, error } = await supabase.from("local_businesses").select("category").limit(1e3);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      result.businesses = tally(data);
    }
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "remix-of-rozgar-sewa-connect",
  title: "Remix of Rozgar sewa  Connect",
  version: "0.1.0",
  instructions: "Read-only tools for RozgarSewa, a platform that connects rural workers, shops, digital service centres and coaching institutes with customers. Use `list_categories` to discover available categories, `search_workers` and `get_worker` for workers, and `search_businesses`, `search_digital_services` and `search_coaching_centres` for local listings. All data returned is public listing information; phone numbers and PINs are not exposed.",
  tools: [
    list_categories_default,
    search_workers_default,
    get_worker_default,
    search_businesses_default,
    search_digital_services_default,
    search_coaching_centres_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
